<?php
if($page=="create-department"){
	$found=include("views/pages/ui/department/create_department.php");
}elseif($page=="edit-department"){
	$found=include("views/pages/ui/department/edit_department.php");
}elseif($page=="manage-department"){
	$found=include("views/pages/ui/department/manage_department.php");
}elseif($page=="details-department"){
	$found=include("views/pages/ui/department/details_department.php");
}elseif($page=="view-department"){
	$found=include("views/pages/ui/department/view_department.php");
}
?>
