<?php
if($page=="create-purchase"){
	$found=include("views/pages/purchase/purchase/create_purchase.php");
}elseif($page=="edit-purchase"){
	$found=include("views/pages/purchase/purchase/edit_purchase.php");
}elseif($page=="purchases"){
	$found=include("views/pages/purchase/purchase/manage_purchase.php");
}elseif($page=="details-purchase"){
	$found=include("views/pages/purchase/purchase/details_purchase.php");
}elseif($page=="view-purchase"){
	$found=include("views/pages/purchase/purchase/view_purchase.php");
}
?>
