<?php
if($page=="create-stockadjustmenttype"){
	$found=include("views/pages/stocks/stockadjustmenttype/create_stockadjustmenttype.php");
}elseif($page=="edit-stockadjustmenttype"){
	$found=include("views/pages/stocks/stockadjustmenttype/edit_stockadjustmenttype.php");
}elseif($page=="stock_adjustment_types"){
	$found=include("views/pages/stocks/stockadjustmenttype/manage_stockadjustmenttype.php");
}elseif($page=="details-stockadjustmenttype"){
	$found=include("views/pages/stocks/stockadjustmenttype/details_stockadjustmenttype.php");
}elseif($page=="view-stockadjustmenttype"){
	$found=include("views/pages/stocks/stockadjustmenttype/view_stockadjustmenttype.php");
}
?>
